version: '3'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres

  db_postgres:
    image: postgres:latest
    container_name: postgres_db_container
    ports:
      - "5433:5433"
    env_file:
      - ./backend/app/.env
