version: '3'

services:
  app:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - db_postgres
    env_file:
      - ./backend/app/.env

  db_postgres:
    image: postgres:latest
    ports:
      - "5434:5432"
    env_file:
      - ./backend/app/.env